#!/usr/bin/env python3
"""Bundle the AI for Accessibility Toolkit catalog into src/browser_harness/a11y/bundle.js.

The toolkit is a sibling checkout, not a submodule, because it is under active
development on the rearch-experiment branch and a submodule would only see
pushed commits. The toolkit's own git HEAD is stamped into the bundle header so
a built artifact still says where it came from.

    python3 scripts/build_a11y.py [--src PATH]

--src defaults to $AI4A11Y_SRC, then to ../AI-for-Accessibility-Toolkit-Draft.
"""
import argparse
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENTRY = ROOT / "src" / "browser_harness" / "a11y" / "entry.js"
OUT = ROOT / "src" / "browser_harness" / "a11y" / "bundle.js"
DEFAULT_SRC = ROOT.parent / "AI-for-Accessibility-Toolkit-Draft"


def toolkit_stamp(src):
    """`<short-sha> <branch>[ dirty]`, or 'unknown' outside a git checkout."""
    def git(*args):
        return subprocess.run(["git", "-C", str(src), *args],
                              capture_output=True, text=True).stdout.strip()
    sha = git("rev-parse", "--short", "HEAD")
    if not sha:
        return "unknown"
    branch = git("rev-parse", "--abbrev-ref", "HEAD") or "detached"
    dirty = " dirty" if git("status", "--porcelain") else ""
    return f"{sha} {branch}{dirty}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default=os.environ.get("AI4A11Y_SRC") or str(DEFAULT_SRC))
    args = ap.parse_args()

    src = Path(args.src).expanduser().resolve()
    if not (src / "tools" / "adapters" / "index.js").exists():
        sys.exit(f"not a toolkit checkout: {src}\n"
                 f"pass --src PATH or set AI4A11Y_SRC")

    esbuild = src / "node_modules" / ".bin" / "esbuild"
    if not esbuild.exists():
        sys.exit(f"esbuild not installed in the toolkit: {esbuild}\n"
                 f"run `npm install` in {src}")

    # esbuild resolves entry.js's imports relative to the file, so the entry has
    # to sit at the toolkit root. Written as a dotfile and removed after.
    staged = src / ".bh-a11y-entry.js"
    staged.write_text(ENTRY.read_text())
    OUT.parent.mkdir(parents=True, exist_ok=True)
    try:
        subprocess.run(
            # Minified: this source is re-parsed by the browser on every
            # navigation, so its size is a per-page cost, not a build artefact.
            [str(esbuild), str(staged), "--bundle", "--format=iife",
             "--platform=browser", "--minify", f"--outfile={OUT}"],
            cwd=str(src), check=True,
        )
    finally:
        staged.unlink(missing_ok=True)

    stamp = toolkit_stamp(src)
    header = f"// generated by scripts/build_a11y.py — toolkit {stamp}\n// source: {src}\n"
    OUT.write_text(header + OUT.read_text())
    print(f"built {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB) from toolkit {stamp}")


if __name__ == "__main__":
    main()
